/* eslint-disable @next/next/no-html-link-for-pages */
import { notFound } from "next/navigation";
import { getClient } from "@/db/client";
import { ManualCorrectionForm, QualificationForm, RecheckButton } from "@/components/Actions";
import { SCORE_CATEGORIES } from "@/domain/scoring";
import { plLabel } from "@/lib/labels";
export const dynamic="force-dynamic";
const labels:Record<string,string>={TEAM:"Zespół i operacyjność",COMPLEXITY:"Wartość i złożoność projektów",GROWTH:"Sygnały wzrostu",MARKETING:"Marketing i sprzedaż",MATURITY:"Dojrzałość i wiarygodność"};
export default async function CompanyPage({params}:{params:Promise<{id:string}>}) {
 const {id}=await params,db=getClient();const company=(await db.query<Record<string,unknown>>("SELECT * FROM companies WHERE id=$1",[id])).rows[0];if(!company)notFound();
 const [evidence,breakdown,errors,answers]=await Promise.all([
  db.query<Record<string,unknown>>("SELECT * FROM evidence WHERE company_id=$1 ORDER BY found_at DESC",[id]),
  db.query<Record<string,unknown>>("SELECT * FROM score_breakdowns WHERE company_id=$1",[id]),
  db.query<Record<string,unknown>>("SELECT * FROM research_errors WHERE company_id=$1 ORDER BY created_at DESC LIMIT 20",[id]),
  db.query<Record<string,string|null>>("SELECT * FROM qualification_answers WHERE company_id=$1",[id])
 ]);
 const missing=[!company.public_email&&"publicznego e-maila",!company.phone&&"publicznego telefonu",!(company.decision_makers as object[]).length&&"publicznego decydenta",company.review_count==null&&"wiarygodnej liczby opinii",!(company.public_job_postings as object[]).length&&"aktualnych ofert pracy",!(company.partnership_levels as string[]).length&&"poziomu partnerstwa"].filter(Boolean);
 const opportunityEvidence=evidence.rows.filter(e=>["MARKETING","GROWTH"].includes(String(e.scoring_category))&&Number(e.awarded_points)>0).slice(0,3);
 return <main><p><a href="/">← Dashboard</a></p><div className="card"><div className="actions" style={{justifyContent:"space-between"}}><div><h1>{String(company.name)}</h1><span className="muted">{String(company.website||"Brak strony")}</span></div><div><span className="score">{String(company.score)}/10</span><br/>{String(company.completeness)}% kompletności</div></div><p><span className="badge good">{plLabel(company.recommendation)}</span> <span className="badge">{plLabel(company.qualification_final_status)}</span></p><RecheckButton id={id}/></div>
 <div className="grid" style={{marginTop:16}}><section className="card"><h2>Dane firmy</h2><dl><dt>Lokalizacja</dt><dd>{[company.city,company.region,company.country].filter(Boolean).join(", ")||"nieznana"}</dd><dt>Kontakt publiczny</dt><dd>{String(company.phone||"brak")} · {String(company.public_email||"brak")}</dd><dt>NIP / KRS</dt><dd>{String(company.nip||"brak")} / {String(company.krs||"brak")}</dd><dt>Technologie</dt><dd>{(company.technologies as string[]).map(x=><span className="badge" key={x}>{x}</span>)||"brak"}</dd><dt>Partnerstwa</dt><dd>{(company.partnership_levels as string[]).join(", ")||"brak"}</dd><dt>Opis usług</dt><dd>{String(company.service_description||"brak")}</dd><dt>Portfolio</dt><dd>{(company.portfolio_urls as string[]).map(x=><div key={x}><a href={x}>{x}</a></div>)}</dd><dt>Opinie</dt><dd>{company.review_count==null?"brak":`${company.review_count} (${company.review_source||"źródło niepodane"})`}</dd><dt>Decydenci</dt><dd><pre>{JSON.stringify(company.decision_makers,null,2)}</pre></dd><dt>Oferty pracy</dt><dd><pre>{JSON.stringify(company.public_job_postings,null,2)}</pre></dd><dt>Źródła pozyskania</dt><dd>{(company.source_urls as string[]).map((x,i)=><div key={x}><a href={x} rel="noreferrer" target="_blank">{(company.source_names as string[])[i]||x}</a></div>)}</dd><dt>Ręczne nadpisania</dt><dd>{Object.keys(company.manual_overrides as object).join(", ")||"brak"}</dd></dl></section>
 <section className="card"><h2>Brakujące dane</h2>{missing.length?<ul className="missing">{missing.map(x=><li key={String(x)}>{String(x)}</li>)}</ul>:<p>Podstawowy zakres danych jest pokryty.</p>}<p className="muted">Kompletność mierzy pokrycie niezależnie potwierdzonych pól i dowodów, nie jakość firmy. Poniżej 50% rekomendacja zawsze brzmi NEEDS_MORE_RESEARCH.</p></section></div>
 <section className="card" style={{marginTop:16}}><h2>Scoring i dowody</h2>{SCORE_CATEGORIES.map(cat=>{const b=breakdown.rows.find(x=>x.category===cat);const ev=evidence.rows.filter(x=>x.scoring_category===cat);return <div key={cat} className="evidence"><strong>{labels[cat]}: {String(b?.points??0)}/2</strong><div>{String(b?.rationale||"Brak publicznego dowodu.")}</div>{ev.map(e=><p key={String(e.id)}><span className="badge">{plLabel(e.confidence)}</span> „{String(e.excerpt)}” — <a href={String(e.source_url)} target="_blank" rel="noreferrer">{String(e.source_url)}</a>, {new Date(String(e.found_at)).toLocaleDateString("pl-PL")}</p>)}</div>})}</section>
 {Number(company.score)>=7&&<section className="card" style={{marginTop:16}}><h2>Dossier do osobistego audytu</h2><p><strong>Podsumowanie:</strong> {String(company.name)}, {String(company.service_description||`publicznie potwierdzone technologie: ${(company.technologies as string[]).join(", ")||"nieznane"}`)}.</p><p><strong>Decydent / kontakt:</strong> {(company.decision_makers as object[]).length?JSON.stringify(company.decision_makers):"nieznany; użyj wyłącznie publicznego kontaktu ogólnego."}</p><p><strong>Najmocniejszy dowód dopasowania:</strong> {String(evidence.rows.sort((a,b)=>Number(b.awarded_points)-Number(a.awarded_points))[0]?.excerpt||"brak wystarczającego dowodu")}</p><p><strong>Zaobserwowane okazje/problemy marketingowo-sprzedażowe:</strong></p>{opportunityEvidence.length?<ul>{opportunityEvidence.map(e=><li key={String(e.id)}>{String(e.excerpt)} (<a href={String(e.source_url)}>dowód</a>)</li>)}</ul>:<p>Nieznane — brak publicznych dowodów pozwalających sformułować tezę.</p>}<p><strong>Spersonalizowany powód kontaktu:</strong> rozmowa o dopasowaniu napływu projektów do potwierdzonego publicznie zakresu: {(company.technologies as string[]).join(", ")||"zakres usług do potwierdzenia"}.</p><p><strong>Pytania:</strong> Czy chcą Państwo więcej projektów? Jakie są moce i plany zatrudnienia? Kto obsługuje i domyka zapytania? Czy właściciel jest wąskim gardłem? Jakich zleceń Państwo szukają, a jakich unikają?</p></section>}
 <section className="card" style={{marginTop:16}}><h2>Korekta ręczna</h2><ManualCorrectionForm id={id} company={company}/></section>
 <div className="grid" style={{marginTop:16}}><section className="card"><h2>Kwalifikacja po rozmowie</h2><QualificationForm id={id} company={company as Record<string,string|null>} answers={answers.rows[0]||{}}/></section><section className="card"><h2>Błędy researchu</h2>{errors.rows.length?errors.rows.map(e=><div className="evidence error" key={String(e.id)}><strong>{String(e.code)}</strong><br/>{String(e.message)}<br/><span className="muted">{String(e.url||e.source_name||"")}</span></div>):<p>Brak zapisanych błędów.</p>}</section></div>
 </main>;
}
