import { getClient } from "@/db/client";
import { BatchButton, CsvImport, SourceManager, UrlImport } from "@/components/Actions";
import { buildCompanyWhere, parseCompanyFilters } from "@/lib/company-filters";
import { plLabel } from "@/lib/labels";
export const dynamic = "force-dynamic";
type Params = Promise<Record<string,string|undefined>>;
export default async function Dashboard({searchParams}:{searchParams:Params}) {
 const p=await searchParams, db=getClient(), filters=parseCompanyFilters(p), built=buildCompanyWhere(filters);
 const companies=await db.query<Record<string,unknown>>(`SELECT * FROM companies ${built.sql} ORDER BY ${built.order},completeness DESC LIMIT 200`,built.values);
 const facets=await db.query<{countries:string[];regions:string[];sources:string[];technologies:string[]}>("SELECT ARRAY(SELECT DISTINCT country FROM companies WHERE country IS NOT NULL ORDER BY 1) AS countries,ARRAY(SELECT DISTINCT region FROM companies WHERE region IS NOT NULL ORDER BY 1) AS regions,ARRAY(SELECT DISTINCT jsonb_array_elements_text(source_names) FROM companies ORDER BY 1) AS sources,ARRAY(SELECT DISTINCT jsonb_array_elements_text(technologies) FROM companies ORDER BY 1) AS technologies");
 const sources=await db.query<{id:string;name:string;enabled:boolean;config:Record<string,string>}>("SELECT id,name,enabled,config FROM research_sources ORDER BY name");
 const query=new URLSearchParams(Object.entries(p).filter((x):x is [string,string]=>typeof x[1]==="string"));query.delete("queue");
 return <main><div className="actions"><a className="button" href="#dodaj">Dodaj źródło</a><BatchButton/><a className="button" href={`/api/export?${query}`}>Eksport widoku</a><a className="button" href={`/api/export?${query}&queue=contact`}>Kolejka kontaktu CSV</a></div>
  <form className="toolbar"><input name="q" defaultValue={p.q} placeholder="Szukaj firmy lub domeny"/><select name="country" defaultValue={p.country}><option value="">Wszystkie kraje</option>{facets.rows[0]?.countries?.map(x=><option key={x}>{x}</option>)}</select><select name="region" defaultValue={p.region}><option value="">Wszystkie regiony</option>{facets.rows[0]?.regions?.map(x=><option key={x}>{x}</option>)}</select><select name="tech" defaultValue={p.tech}><option value="">Wszystkie technologie</option>{facets.rows[0]?.technologies?.map(x=><option key={x}>{x}</option>)}</select><select name="source" defaultValue={p.source}><option value="">Wszystkie źródła</option>{facets.rows[0]?.sources?.map(x=><option key={x}>{x}</option>)}</select><select name="minScore" defaultValue={p.minScore}><option value="">Dowolny wynik</option>{[4,7,9].map(x=><option key={x} value={x}>Od {x}</option>)}</select><select name="sort" defaultValue={p.sort||"desc"}><option value="desc">Wynik malejąco</option><option value="asc">Wynik rosnąco</option></select><label><input type="checkbox" name="best" value="1" defaultChecked={p.best==="1"}/> Najlepsze leady</label><button>Filtruj</button></form>
  <div className="table-wrap"><table><thead><tr><th>Firma</th><th>Wynik</th><th>Kompletność</th><th>Rekomendacja / status</th><th>Technologie</th><th>Lokalizacja / źródło</th><th>Ostatnio</th></tr></thead><tbody>{companies.rows.map(c=><tr key={String(c.id)}><td><a href={`/companies/${c.id}`}><strong>{String(c.name)}</strong></a><br/><span className="muted">{String(c.domain||c.website||"brak strony")}</span></td><td><span className="score">{String(c.score)}/10</span></td><td>{String(c.completeness)}%</td><td><span className={`badge ${c.recommendation==="PERSONAL_AUDIT"?"good":"warn"}`}>{plLabel(c.recommendation)}</span><br/>{plLabel(c.qualification_final_status)}</td><td>{(c.technologies as string[]).map(x=><span className="badge" key={x}>{x}</span>)}</td><td>{[c.city,c.region,c.country].filter(Boolean).join(", ")}<br/><span className="muted">{(c.source_names as string[]).join(", ")}</span></td><td>{c.checked_at?new Date(String(c.checked_at)).toLocaleDateString("pl-PL"):"nigdy"}</td></tr>)}</tbody></table></div>
  {!companies.rows.length&&<p className="card">Brak firm. Dodaj publiczny URL albo zaimportuj CSV.</p>}
  <section id="dodaj" className="grid" style={{marginTop:24}}><div className="card"><h2>Dodaj publiczną stronę</h2><UrlImport/></div><div className="card"><h2>Import CSV</h2><p className="muted">Do 2 MB i 1000 wierszy; polskie lub kanoniczne nagłówki.</p><CsvImport/><p><a href="/sample/firmy.csv">Pobierz przykład</a></p></div><div className="card"><h2>Katalogi publiczne</h2><SourceManager sources={sources.rows}/></div></section>
 </main>;
}
